-- SQL Schema untuk tabel terpisah 'workforce' pada Supabase
-- Silakan salin (copy) seluruh kode di bawah ini dan tempelkan (paste) ke dalam Supabase SQL Editor Anda:
-- Dashboard Supabase -> SQL Editor -> New Query -> Paste -> Run

-- 1. Buat Tabel 'workforce'
CREATE TABLE IF NOT EXISTS public.workforce (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nip VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    skill VARCHAR(255) DEFAULT 'English',
    channel VARCHAR(255) DEFAULT 'Voice',
    gender VARCHAR(255) DEFAULT 'Male',
    religion VARCHAR(255) DEFAULT 'Islam',
    project VARCHAR(255) DEFAULT 'Project Alpha',
    unit VARCHAR(255) DEFAULT 'Unit A',
    site VARCHAR(255) DEFAULT 'Jakarta',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Aktifkan Row Level Security (RLS) jika diinginkan agar aman
ALTER TABLE public.workforce ENABLE ROW LEVEL SECURITY;

-- 3. Buat Kebijakan Akses (Security Policies) agar dapat diakses oleh client anonim/terotentikasi
-- Policy: Mengizinkan semua orang membaca data (Select)
CREATE POLICY "Allow public read access" 
ON public.workforce 
FOR SELECT 
USING (true);

-- Policy: Mengizinkan semua orang menambah data (Insert)
CREATE POLICY "Allow public insert access" 
ON public.workforce 
FOR INSERT 
WITH CHECK (true);

-- Policy: Mengizinkan semua orang memperbarui data (Update)
CREATE POLICY "Allow public update access" 
ON public.workforce 
FOR UPDATE 
USING (true)
WITH CHECK (true);

-- Policy: Mengizinkan semua orang menghapus data (Delete)
CREATE POLICY "Allow public delete access" 
ON public.workforce 
FOR DELETE 
USING (true);

-- 4. Buat Tabel 'interval_requirements'
CREATE TABLE IF NOT EXISTS public.interval_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    time_slot VARCHAR(255) NOT NULL,
    required_agents INTEGER DEFAULT 0 NOT NULL,
    interval_type VARCHAR(50) DEFAULT '1h' NOT NULL, -- '15m', '30m', '1h'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    -- Unique constraint agar data tidak duplikat untuk slot, tanggal, jenis interval yang sama
    CONSTRAINT unique_requirement UNIQUE (date, time_slot, interval_type)
);

-- 5. Aktifkan Row Level Security (RLS)
ALTER TABLE public.interval_requirements ENABLE ROW LEVEL SECURITY;

-- 6. Buat Kebijakan Akses (Security Policies) agar dapat diakses oleh client anonim / terotentikasi
CREATE POLICY "Allow public read interval_requirements" 
ON public.interval_requirements FOR SELECT USING (true);

CREATE POLICY "Allow public insert interval_requirements" 
ON public.interval_requirements FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update interval_requirements" 
ON public.interval_requirements FOR UPDATE USING (true) WITH CHECK (true);

CREATE POLICY "Allow public delete interval_requirements" 
ON public.interval_requirements FOR DELETE USING (true);


-- 7. Buat Tabel 'master_shifts' (Tabel Terpisah untuk Master Shift Registry)
CREATE TABLE IF NOT EXISTS public.master_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project VARCHAR(255) NOT NULL, -- Nama project yang terkoneksi pada DB workforce
    code VARCHAR(50) NOT NULL, -- Kode Shift (misal: S1, P2, M1)
    start_time VARCHAR(10) NOT NULL, -- Jam Mulai (misal: '07:00')
    end_time VARCHAR(10) NOT NULL, -- Jam Selesai (misal: '16:00')
    weight INTEGER DEFAULT 1 NOT NULL, -- Weight / bobot shift (misal: 1, 2)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_project_shift_code UNIQUE (project, code)
);

-- 8. Aktifkan Row Level Security (RLS) untuk master_shifts
ALTER TABLE public.master_shifts ENABLE ROW LEVEL SECURITY;

-- 9. Buat Kebijakan Akses (Security Policies) untuk master_shifts
CREATE POLICY "Allow public read master_shifts" 
ON public.master_shifts FOR SELECT USING (true);

CREATE POLICY "Allow public insert master_shifts" 
ON public.master_shifts FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update master_shifts" 
ON public.master_shifts FOR UPDATE USING (true) WITH CHECK (true);

CREATE POLICY "Allow public delete master_shifts" 
ON public.master_shifts FOR DELETE USING (true);


