name: Push to Repo A Otomatis

# Baris ini mengatur kapan otomatisasi berjalan
# Di sini diatur setiap kali ada "push" ke branch "main"
on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositori B
        uses: actions/checkout@v4 # Diubah ke v4 untuk mengatasi warning Node.js
        with:
          fetch-depth: 0

      - name: Push kode ke Repositori A
        env:
          # HAPUS https:// agar tidak dobel. Tambahkan .git di belakangnya
          TARGET_REPO: "https://github.com/taqienahmad/TransForce-Management-Dashboard" 
          TARGET_BRANCH: "main"
        run: |
          # Menambahkan Repositori A sebagai tujuan dengan menggunakan Token Rahasia
          git remote add repo-a https://${{ secrets.PAT_REPO_A }}@$TARGET_REPO
          
          # Mendorong kode dari Repo B ke Repo A
          git push repo-a HEAD:$TARGET_BRANCH --force
