name: Push to Repo A Otomatis

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push kode ke Repositori A
        env:
          # Pastikan URL ini sudah benar dan akun tujuan mengizinkan push
          TARGET_REPO: "https://github.com/taqienahmad/TransForce-Management-Dashboard"
          TARGET_BRANCH: "main"
        run: |
          # Menghapus origin jika ada konflik
          git remote rm repo-a || true
          
          # Menambahkan remote dengan token
          git remote add repo-a https://${{ secrets.PAT_REPO_A }}@$TARGET_REPO
          
          # Paksa dorong ke main
          git push repo-a HEAD:$TARGET_BRANCH --force
